Repository KGUCapstone/frontend, pull requests merged in 2025-04, with the labels that each got.

#10 Feat: 장바구니 페이지 및 기능, 내정보 페이지 추가
  package-lock.json
  package.json
  src/App.js
  src/pages/CartList.js
  src/pages/ComparePage.js
  src/pages/MyPage.js
  src/style/CartList.css
  src/style/HomeButton.css
  src/style/MainPage.css
  src/style/MyPage.css
Labels: feature

#11 Feat: 장바구니 서버 연결 및 기록 페이지 추가
  package-lock.json
  package.json
  src/App.js
  src/components/BottomNav.js
  src/pages/CartDetailPage.js
  src/pages/CartList.js
  src/pages/ComparePage.js
  src/pages/HistoryPage.js
  src/style/HoverUnderline.css
Labels: enhancement, feature

#12 Feat: 검색 시 텍스트만, 사진 촬영 시 이미지와 텍스트 동시 제공 기능추가
  src/components/SearchBar.js
  src/pages/ComparePage.js
  src/pages/PicturePage.js
Labels: feature

#17 Feat: Home.css 추가 및 스타일 수정, 레이아웃 조정
  src/assets/logo.svg
  src/assets/naver_logo.svg
  src/assets/title.svg
  src/pages/CameraPage.js
  src/pages/Home.js
  src/style/AuthForm.css
  src/style/CameraPage.css
  src/style/Home.css
Labels: feature

#13 Feat: 네이버 쇼핑 연결, 상세 비교 페이지 추가, 비교 페이지에서 cartList로 넘어갈 때 항목 누락 수정
  src/App.js
  src/pages/CartList.js
  src/pages/ComparePage.js
  src/pages/cartDetailList.js
  src/style/CartList.css
  src/style/ComparePage.css
  src/style/cartDetailList.css
Labels: feature

#22 Feat: 마이페이지 기능 수정
  package-lock.json
  package.json
  src/assets/areachart.svg
  src/assets/barchart.svg
  src/assets/linechart.svg
  src/pages/MyPage.js
  src/style/MyPage.css
Labels: feature

#23 Fix: 텍스트 검색시 텍스트, 이미지 검색 시 이미지+텍스트 출력 수정
  package-lock.json
  package.json
  src/pages/ComparePage.js
Labels: fix

#24 Feat: 장바구니 상품 수량 추가 및 오프라인/매장 상품과 온라인 가격 비교
  src/App.js
  src/components/BottomNav.js
  src/components/CartItem.js
  src/components/SearchBar.js
  src/pages/CameraPage.js
  src/pages/CartDetailPage.js
  src/pages/CartList.js
  src/pages/CheckListPage.js
  src/pages/ComparePage.js
  src/pages/HistoryPage.js
  src/pages/MyPage.js
  src/pages/PicturePage.js
  src/pages/SavedAmountPage.js
  src/style/CartItem.css
  src/style/CartList.css
  src/style/SavedAmountPage.css
Labels: enhancement, feature

#29 Feat: 체크리스트 비교하기 버튼 전까지 구현
  src/pages/CheckListPage.js
  src/style/CheckListPage.css
Labels: feature
