Repository KGUCapstone/frontend, pull requests merged in 2025-05, with the labels that each got.

#31 메인페이지 기반 디자인 수정
  src/assets/areachart.svg
  src/assets/barchart.svg
  src/assets/linechart.svg
  src/assets/profile.svg
  src/pages/CameraPage.js
  src/pages/Home.js
  src/pages/JoinForm.js
  src/pages/LoginForm.js
  src/pages/MainPage.js
  src/pages/MyPage.js
  src/style/CameraPage.css
  src/style/Home.css
  src/style/LoginForm.css
  src/style/MainPage.css
  src/style/ModalSearch.css
  src/style/MyPage.css
Labels: fix

#35 Feat: 체크리스트 페이지 구조 재수정 및 장바구니 담기 기능 추가
  src/components/CartItem2.js
  src/pages/CheckListPage.js
  src/pages/ComparisonResultsPage.js
  src/style/CartItem2.css
  src/style/CheckListPage.css
  src/style/ComparisonResultsPage.css
  src/style/MainPage.css
Labels: feature, fix

#32 Feat : checklist 페이지들 구조 수정
  src/pages/CheckListPage.js
  src/pages/ComparisonResultsPage.js
  src/style/CheckListPage.css
  src/style/ComparisonResultsPage.css
Labels: feature

#37 Design: 헤더 및 네비 메뉴 통일, 카드 위치 일부 통일
  src/pages/CartList.js
  src/pages/CheckListPage.js
  src/pages/ComparisonResultsPage.js
  src/style/CartList.css
  src/style/CheckListPage.css
  src/style/ComparisonResultsPage.css
  src/style/MainPage.css
Labels: fix

#34 Feat: ComparePage 구조 수정
  src/components/CartItem.js
  src/pages/ComparePage.js
  src/pages/MainPage.js
  src/style/ComparePage.css
Labels: feature

#41 Fix: ComparePage 체크박스 범위 수정 및 CartDetailPage 상품 출력 일부 수정
  src/components/CartItem.js
  src/style/ComparePage.css
Labels: fix

#54 Feat: 홈버튼 위치 수정 및 체크리스트 페이징 적용
  src/components/BottomNav.js
  src/pages/CheckListPage.js
  src/style/BottomNav.css
  src/style/CheckListPage.css
  src/style/ComparePage.css
  src/style/ComparisonResultsPage.css
Labels: feature, fix
